"""
host.py - the engine's side of the script interface, and a stage that runs.

[`squirrel.py`](squirrel.py) executes the game's own bytecode.
[`format_api.md`](../docs/format_api.md) says what the 285 functions it calls
are for. This is the other side of that document: the 285 bound to something,
the `suspend` protocol turned into a scheduler, and a loop that loads a stage,
runs its script, walks a body across it and lets the trigger volumes fire.

    python engine/host.py stage  extract/tree 010_01_01 [quest] [class json]
    python engine/host.py demo   extract/tree [010_01_01]
    python engine/host.py talk   extract/tree No13800.psq
    python engine/host.py stages extract/tree
    python engine/host.py api    extract/tree

`stage` is milestone 2. `stages` runs the first half of it - load the world,
load the scripts, call `sfStageInit()` - on **every** stage on the disc, which
is the only way to find out whether the reading generalises. `api` reports how
much of the interface any of that reaches.

Milestone 5 is [`mission.py`](mission.py), which plugs a quest's four tables
into the `spawner` slot below and turns nine of these calls from recorders
into state that moves.

## What "bound" means here, and what it does not

Of the 285, **70 do something** - and they carry 17,862 of the 25,699 calls
the disc makes, which is 70% of the interface's traffic: they move the body,
read the marker table, toggle a fence or a spawner, keep a flag bank, jump to
another stage, spawn what a quest declares, or hand
back a number the disc says they hand back. The rest are recorded and return
0 - which is a stub, and the report says so every time it prints a count.

Returning 0 rather than null is deliberate: nearly every one of these answers
a question with a number, and a null turns the script's first comparison into
an error and hides everything after it.

Four of the seventy answer with a number **only when a quest layer is
loaded**: `cfGetCntKillGenPieceLockOnly`, `getLatestKilled`, `getNumOfEnemy`
and `getNumOfBoss` are what a quest script asks about what is alive, and
[`mission.py`](mission.py)'s `Spawner` is what knows. Without one they behave
as they always did, which is to say they return 0.

The 285 are listed in `NATIVES` with the number of calls each gets across the
disc, so the file declares the whole interface whether or not it implements
it. That list is generated from the bytecode, not typed: it is every name
fetched off the root table and called that no `.psq` defines, less Squirrel's
own five and `prowl_script`, which is the hole
[`format_api.md`](../docs/format_api.md) describes.

## The suspend vocabulary is a scheduler

A blocking call is `cfTalk(...); suspend(101)`. The host gets 101, knows a
talk line is on screen, waits, and resumes the thread - with a value where
the script reads one. `RESUME` is that table: for each of the thirteen
numbers, how many frames the host holds it and what the script gets back.
The numbers come from [`format_api.md`](../docs/format_api.md); the delays are
this file's own policy and are marked as such, because nothing on the disc
says how long a talk line stays up.

`wait(n)` is `setWaitCount(n); suspend(1000)`, and that one is not policy: the
count is the script's and the host owes it exactly that many frames.

## What a trigger is

`trigger.trg` pairs an `hta.bin` marker with a line of Squirrel source -
`MapJumpA(); callQuestScript("sfEnmGenStart()");` on `010_01_01`. The volume
is an oriented box in the marker table, the event is enter or leave
([`format_stage.md`](../docs/format_stage.md)), and the source is a sequence
of calls with constant arguments. `call_line` parses that much and no more: it
is not a compiler, and a trigger it cannot read is reported rather than
skipped.
"""
from __future__ import annotations

import fnmatch
import inspect
import math
import pathlib
import random
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent
                       / 'tools'))

if hasattr(sys.stdout, 'reconfigure'):      # a third of this build's
    sys.stdout.reconfigure(encoding='utf-8',           # own debug
                           errors='backslashreplace')
                                           # output is Japanese

from actor import FPS, Actor, bearing, load as load_params    # noqa: E402
from squirrel import (Array, Closure, Native, SquirrelError, Table,   # noqa: E402
                      Thread, VM, VMError, globals_called, to_string)
from psq import Psq                                           # noqa: E402
from rmsg import Rmsg                                         # noqa: E402
from world import World                                       # noqa: E402

# The 285. The number beside each is how many times the disc calls it, which
# is what says whether a stub is cheap or expensive. Generated by
# `python engine/host.py api`.
NATIVES = {
    'EffData': 6, 'SoundManager_getInstance': 3, 'Vec3': 2,
    'callQuestScriptPC': 34, 'cfAddEmGenWait': 22, 'cfAddItem': 10,
    'cfAnimeIcon': 3, 'cfCheckDictionaryReward': 1, 'cfCheckEqAceSkill': 1,
    'cfCheckEqCard': 2, 'cfCheckMyOrderClear': 1, 'cfCheckQuestStart': 1,
    'cfCheckShopOpenItemFlag': 8, 'cfCheckShopOpenNewItem': 2,
    'cfChoice': 1, 'cfChoiceFreedom': 1, 'cfCmrQuake': 57,
    'cfDialogButton': 1, 'cfDialogEnd': 1, 'cfDialogMessage': 1,
    'cfDialogParam': 1, 'cfDialogParamAll': 35, 'cfDialogStart': 1,
    'cfEmo': 1, 'cfEnableCmrHoming': 4, 'cfEndPieceLock': 732,
    'cfExtendEqCloth': 1, 'cfGetBillingStatus': 1,
    'cfGetCntKillGenPieceLockOnly': 892, 'cfGetFreeCardSlot': 10,
    'cfGetGlobalFlag': 1227, 'cfGetJob': 9, 'cfGetMainCounter': 181,
    'cfGetNornFeeling': 61, 'cfGetPosInHta': 40, 'cfGetQuestFlag': 908,
    'cfGetRandF': 4, 'cfGetRandI': 2, 'cfInfoChapterClear': 1,
    'cfInheritCameraSettingOnce': 2, 'cfIsBarMenuAccess': 12,
    'cfIsBarQuestSelected': 50, 'cfIsEmptyInClosetWeapon': 3,
    'cfIsMulti': 27, 'cfIsMultiError': 12, 'cfIsMultiStart': 6,
    'cfIsQuestClear': 3, 'cfIsQuestClearByIDFlag': 10,
    'cfIsQuestSelect': 117, 'cfLowBarClosetAccess': 1,
    'cfLowBarQuestAccess': 98, 'cfLowBarShopAccess': 70, 'cfMapJump': 176,
    'cfMapJumpForce': 17, 'cfPadEndFocus': 260, 'cfPadFocusReset': 10,
    'cfPadStartFocus': 265, 'cfQuitBarJump': 21, 'cfRecvDlc': 1,
    'cfRecvNear': 1, 'cfRecvNearMyGift': 1, 'cfRefineEqWeapon': 1,
    'cfRename': 1, 'cfResetCmrFov': 12, 'cfResetCmrReserve': 7,
    'cfResetShopOpenItemFlag': 2, 'cfReviveEmGen': 8,
    'cfSetBarClosetAccess': 1, 'cfSetBarQuestAccess': 49,
    'cfSetBarShopAccess': 70, 'cfSetCameraType': 330, 'cfSetClearColor': 6,
    'cfSetCmrAngX': 35, 'cfSetCmrAngXDeg': 65, 'cfSetCmrAngY': 60,
    'cfSetCmrAngYDeg': 64, 'cfSetCmrFortressTalkMode': 127,
    'cfSetCmrFov': 59, 'cfSetCmrPos': 83, 'cfSetCmrPosIndividual': 83,
    'cfSetEnableBorderline': 687, 'cfSetEnableEmGen': 240,
    'cfSetEnableHitArea': 1460, 'cfSetEnemyAttendType': 6,
    'cfSetEnemyMax': 6, 'cfSetGlobalFlag': 1476, 'cfSetJobItem': 9,
    'cfSetMainCounter': 26, 'cfSetQuestFlag': 1730,
    'cfSetQuestUnselect': 9, 'cfSetShopDialogFlg': 28, 'cfShopBarber': 1,
    'cfShopBottle': 1, 'cfShopCannon': 1, 'cfShopCard': 1,
    'cfShopGoods': 1, 'cfShopPipe': 1, 'cfShopQuest': 1,
    'cfShopQuestCancel': 1, 'cfShopSewing': 1, 'cfShopSmith': 1,
    'cfSndPlayBGM': 22, 'cfSndPlayCmnSE': 21,
    'cfSndPlayCmnSE_useStgPlayer': 2, 'cfSndPlaySE': 21,
    'cfSndPlayStgBGM': 16, 'cfSndPlayStgBGMOW': 197, 'cfSndPlayStgSE': 39,
    'cfSndPlayStgSE3D': 2, 'cfSndPlayVoiceNPC': 69, 'cfSndStopBGM': 184,
    'cfSndVolumeBGM': 3, 'cfSndVolumeCategory': 59,
    'cfStartPieceLock': 889, 'cfStartQuest': 9, 'cfSubNornFeeling': 49,
    'cfTalk': 2, 'cfTalkClose': 1, 'cfTalkOpen': 1, 'cfTalk_end': 1,
    'cfTestVec3': 1, 'cfTutorialLineup': 2, 'cfTutorialLineupMode': 2,
    'cfUpdateNornAccess': 49, 'changeEnemySet': 23, 'checkB01Term': 6,
    'checkB05Term': 6, 'checkB09Term': 6, 'checkB11Term': 6,
    'checkB15Term': 6, 'checkB18Term': 6, 'checkB19Term': 9,
    'checkRangeParam': 18, 'chrChangeMotion': 348, 'chrFreeze': 1,
    'chrGetRot': 1, 'chrPlayVoice': 1193, 'chrRotOpponent': 8,
    'chrSetAlpha': 26, 'chrSetAttachArticle': 12, 'chrSetDir': 109,
    'chrSetFromHta': 8, 'chrSetMotion': 901, 'chrSetMotionNPC': 502,
    'chrSetPos': 85, 'chrSetRot': 84, 'chrSignalIcon': 64, 'chrVisible': 1,
    'clearCrossSaveExplainTime': 1, 'continueYggdrasillQuest': 1,
    'delayScriptCall': 1, 'effSetPauseMapEff': 4, 'effSetPos': 1,
    'effSetRot': 1, 'effStart': 1, 'endDemoTelop': 26, 'getAIType': 21,
    'getActSuccessCount': 12, 'getActionLastFrame': 68,
    'getActiveSameKindCount': 6, 'getAngleTypeAtTarget': 12,
    'getAngleTypeToTarget': 6, 'getBossTime': 12, 'getCharacter': 1609,
    'getCountAnimeIcon': 2, 'getCrossSaveExplainTime': 1,
    'getCurrentYggdrasillFloorNo': 7, 'getDamageFromTarget': 6,
    'getDamagedCount': 18, 'getDemoFrame': 68, 'getDemoGlobalFlag': 1,
    'getFailedActCount': 6, 'getHTAPos': 1, 'getHeight': 52,
    'getHpRate': 122, 'getInt': 5, 'getLastActId': 18,
    'getLatestFinishReason': 12, 'getLatestKilled': 23,
    'getLockTargetRange': 6, 'getNearestBossAction': 180,
    'getNearestBossKind': 252, 'getNumOfBoss': 88, 'getNumOfEnemy': 110,
    'getNumOfUnderHpRate': 2, 'getOtherBossCount': 7,
    'getOtherZakoCount': 13, 'getPartsDamageCount': 18,
    'getPartyMemberHpRate': 6, 'getPlaneRange': 304, 'getPlayerCount': 6,
    'getQuestName': 72, 'getRand': 1010, 'getRange': 216,
    'getSampleFloatArray3': 1, 'getSampleFloatArray4': 1,
    'getSampleIntArray2': 1, 'getScale': 6, 'getSelRevise': 6,
    'getStaggerCount': 6, 'getTargetActId': 180, 'getTargetArea': 6,
    'getTargetHpRate': 7, 'getTargetJob': 6, 'getTargetMonsterKind': 108,
    'getTargetPosy': 11, 'getTargetRange': 18, 'getTargetType': 140,
    'getTime': 34, 'getTimeFromID': 12, 'getTotalTime': 6,
    'getYggdrasillPieceType': 2, 'initDemoTelop': 43,
    'inquireDemoTriggerType': 1, 'isAbnormal': 36, 'isActive': 18,
    'isAngry': 12, 'isAngryReq': 6, 'isAvailableAceSkill': 28,
    'isBossToTarget': 6, 'isDemoMode': 18, 'isDestroyedParts': 260,
    'isDowned': 7, 'isEnableCrossSave': 1, 'isFailedRotation': 6,
    'isPS3': 1, 'isPlayPhonographPlay': 1, 'isPoison': 6, 'isReact': 6,
    'isRecoverFaint': 6, 'isRecoverParalyz': 6, 'isRecoverPoison': 6,
    'isTargetAttack': 6, 'isTargetDamage': 6, 'isTargetDown': 7,
    'isTargetGround': 8, 'isTargetGuard': 6, 'isTargetJump': 7,
    'isTargetObject': 6, 'isTargetSway': 6, 'isToActive': 6, 'isVITA': 1,
    'isYggdrasillClimbing': 6, 'moveRecycleBox': 69,
    'notifyPipeModeEnd': 71, 'notifyRecycleModeEnd': 40,
    'npcRelocation': 32, 'npcSignalIcon': 19, 'openCloset': 1,
    'openMusicPlayer': 1, 'openPipeModeGoods': 1, 'openPipeModeSewing': 1,
    'openPipeModeSmith': 1, 'openRecycleBox': 1, 'openRecycleModeCon': 8,
    'openRecycleModeOttal': 1, 'openRoomSelect': 1, 'openSaveArea': 1,
    'openShopBilling': 1, 'openSpectroLight': 1, 'openTutorial': 3,
    'printAitIdName': 6, 'setBlackFade': 247, 'setDemoBGM': 68,
    'setDemoEnd': 88, 'setDemoHook': 2, 'setDemoID': 290,
    'setDemoMode': 12, 'setDemoMotion': 68, 'setDemoObiHeight': 136,
    'setDemoPause': 52, 'setDemoPos': 68, 'setDemoRotY': 68,
    'setDemoVisible': 55, 'setHTAFlag': 153, 'setInt': 7,
    'setShieldEnable': 3, 'setShieldMotion': 3, 'setSuccessiveBattle': 20,
    'setWaitCount': 1, 'setWhiteFade': 27, 'startDemoTelop': 60,
    'talk_begin': 1072, 'visibleFieldInfo': 176, 'visibleMiniMapCamera': 8,
}

# The suspend vocabulary of `format_api.md`, and what the host does with it.
# The frame counts are policy - nothing on the disc says how long a talk line
# is up - and the values are what the script reads back.
RESUME = {
    100: (0, None, 'a talk window opened'),
    101: (30, None, 'a talk line is on screen'),
    110: (0, 0, 'a choice - the host picks the first'),
    120: (0, None, 'a full-screen mode'),
    140: (0, 0, 'the room selector'),
    150: (0, 65535, 'the shop pipe menu - cancelled'),
    200: (0, None, 'a tutorial image'),
    201: (0, 0, 'the tutorial line-up'),
    300: (0, None, 'a dialog opened'),
    301: (0, None, 'a dialog closed'),
    302: (30, None, 'a dialog message'),
    400: (0, 1, 'the quest-start dialog - the host says yes'),
    1000: ('wait', None, 'a plain wait'),
    1100: (0, None, 'the recycle box'),
}

# `misc.cpk/psq_common.pac` is the resident library: 85 functions over the
# interface, and the five files define no name twice, which is what says they
# are meant to be loaded together.
LIBRARY = ('common.psq', 'class.psq', 'stage.psq', 'quest.psq', 'test.psq')
COMMON = 'misc.cpk/psq_common.pac/common.psq'
TALK_MSG = 'menu.cpk/msg_field.en.pac/msg_npc_talk.bin'
TALK_WHO = 'menu.cpk/msg_common.en.pac/msg_npc.bin'
# A cutscene's length is the `u16` at 0x10 of its camera track, the same
# place [`format_cnom.md`](../docs/format_cnom.md) reads a motion's length.
# 226 to 1,081 frames over the 78 tracks, which is 7.5 to 36 seconds.
CSCM_FRAMES = 0x10

# `getCharacter` names an `hta.bin` marker with this in front of it: 1,362 of
# 1,407 testable calls resolve that way.
CHR_PREFIX = 'pos_'


# -- the trigger language --------------------------------------------------

NAME = re.compile(r'\s*([A-Za-z_]\w*)\s*\(')


def call_line(text: str):
    """`MapJumpA(); callQuestScript("sfEnmGenStart()");` as (name, args).

    A trigger's script field is Squirrel source with constant arguments and
    nothing else - no operators, no locals - on all 508 triggers the disc
    ships. The argument may itself be a line of source in a string, which is
    why the closing bracket has to be found with the quotes respected and not
    with a regular expression: 147 of the 508 are
    `callQuestScript("<something>()")` and a lazy bracket match reads them as
    ending inside the string.

    Anything richer than a call with constant arguments belongs in the VM,
    and this returns None for it rather than guessing."""
    out, pos = [], 0
    while pos < len(text):
        if not text[pos:].strip():
            break
        m = NAME.match(text, pos)
        if not m:
            return None
        end = _closing(text, m.end() - 1)
        if end is None:
            return None
        args = []
        for a in _split_args(text[m.end():end]):
            v = _literal(a)
            if v is _BAD:
                return None
            args.append(v)
        out.append((m.group(1), args))
        pos = end + 1
        while pos < len(text) and text[pos] in ' \t\r\n;':
            pos += 1
    return out


def _closing(text, open_at):
    """The `)` that matches the `(` at `open_at`, ignoring brackets inside
    string literals."""
    depth, quote = 0, ''
    for i in range(open_at, len(text)):
        c = text[i]
        if quote:
            if c == quote:
                quote = ''
            continue
        if c in '"\'':
            quote = c
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return i
    return None


_BAD = object()


def _split_args(s: str):
    out, depth, cur, quote = [], 0, '', ''
    for c in s:
        if quote:
            cur += c
            if c == quote:
                quote = ''
            continue
        if c in '"\'':
            quote = c
            cur += c
        elif c == '(':
            depth += 1
            cur += c
        elif c == ')':
            depth -= 1
            cur += c
        elif c == ',' and depth == 0:
            out.append(cur)
            cur = ''
        else:
            cur += c
    if cur.strip():
        out.append(cur)
    return [a.strip() for a in out if a.strip()]


def _literal(a: str):
    if len(a) >= 2 and a[0] == a[-1] and a[0] in '"\'':
        return a[1:-1]
    try:
        return int(a, 0)
    except ValueError:
        pass
    try:
        return float(a)
    except ValueError:
        return _BAD


def _arity(fn):
    """How many positional arguments a binding takes, at least and at most."""
    if fn is None:
        return 0, 0
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError):
        return 0, 99
    lo = hi = 0
    for p in sig.parameters.values():
        if p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD):
            return lo, 99
        if p.kind in (p.POSITIONAL_ONLY, p.POSITIONAL_OR_KEYWORD):
            hi += 1
            if p.default is p.empty:
                lo += 1
    return lo, hi


# -- geometry --------------------------------------------------------------


def inside(marker, x, y, z) -> bool:
    """Is a point inside a marker's oriented box? The rotation is a triple
    but only the Y of it turns a footprint, and 1,432 markers stand upright."""
    dx, dy, dz = x - marker.position[0], y - marker.position[1], \
        z - marker.position[2]
    a = math.radians(marker.rotation[1])
    ca, sa = math.cos(a), math.sin(a)
    lx = dx * ca - dz * sa
    lz = dx * sa + dz * ca
    ex, ey, ez = marker.extents
    return abs(lx) <= ex and abs(lz) <= ez and abs(dy) <= max(ey, 2.0)


# -- the host --------------------------------------------------------------


class Character:
    """What `getCharacter` hands back: a name, and the marker it stands on."""

    def __init__(self, name, marker=None):
        self.name = name
        self.marker = marker
        self.x, self.y, self.z = marker.position if marker else (0.0, 0.0, 0.0)
        self.rot = marker.rotation[1] if marker else 0.0
        self.motion = None
        self.visible = True

    def __repr__(self):
        return '(character %s)' % self.name


class Host:
    """One running game: a world, a VM, the flag banks and the scheduler."""

    def __init__(self, tree, quest='', seed=1, verbose=True, spawner=None):
        self.tree = pathlib.Path(tree)
        self.vm = VM(printer=self._print)
        self.quest = quest
        self.rng = random.Random(seed)
        self.verbose = verbose
        self.frame = 0
        self.log = []
        self.events = []
        self.stub_calls = {}                    # name -> how many times
        self.real_calls = {}
        self.arity = {}                         # ... with the wrong count
        self.implemented = set()                # the ones that do something
        self.wanted = set()                     # every name the scripts call
        self.steps = 0                          # instructions retired
        # state the interface keeps
        self.global_flags = {}
        self.quest_flags = {}
        self.ints = {}
        self.main_counter = 11000
        self.wait_count = 0
        self.hit_areas = {}                     # name -> enabled
        self.fences = {}
        self.spawners = {}
        self.piece_lock = None
        self.characters = {}
        self.demo = {}
        self.camera = {'type': 0, 'fov': None}
        self.bgm = None
        self.effects = []
        self.threads = []                       # (thread, wake frame, why)
        self.world = None
        self.stage_name = ''
        self.pending_jump = None
        self.loaded = []
        # The quest layer, when there is one: `mission.py`'s `Spawner`, which
        # owns `enemy_gen.bin`, `enemy.bin` and `piecelock.bin` and turns
        # nine of the calls below from recorders into state that moves.
        # Without it they behave exactly as they did before.
        self.spawner = spawner
        if spawner is not None:
            spawner.host = self
        self.bind()

    @property
    def missing(self):
        """Names the loaded scripts call that nothing here answers. A name
        another `.psq` defines is not missing - it is not loaded."""
        return {n for n in self.wanted if n not in self.vm.root.slots}

    # -- output ------------------------------------------------------------

    def _print(self, s):
        for line in s.splitlines():
            if line:
                self.note('print', line)

    def note(self, kind, text):
        self.events.append((self.frame, kind, text))
        if self.verbose:
            print('  %5d  %-8s %s' % (self.frame, kind, text))

    # -- the interface -----------------------------------------------------

    def bind(self):
        """Every one of the 285: the ones that do something first, then the
        rest as recorders."""
        real = {
            # flags, progress and the save
            'cfGetGlobalFlag': lambda i: self.global_flags.get(int(i), 0),
            'cfSetGlobalFlag': lambda i, v: self.global_flags.__setitem__(
                int(i), v),
            'cfGetQuestFlag': lambda i: self.quest_flags.get(int(i), 0),
            'cfSetQuestFlag': lambda i, v: self.quest_flags.__setitem__(
                int(i), v),
            'cfGetMainCounter': lambda: self.main_counter,
            'cfSetMainCounter': self._set_counter,
            'getInt': lambda bank, slot: self.ints.get((int(bank),
                                                        int(slot)), 0),
            'setInt': lambda bank, slot, v: self.ints.__setitem__(
                (int(bank), int(slot)), v),
            'getQuestName': lambda: self.quest,
            'cfIsQuestSelect': lambda: 1 if self.quest else 0,
            'cfIsQuestClear': lambda name: 0,
            'getHardwareType': lambda: 0,       # 0 is the PS3; isVITA is 0
            'isPS3': lambda: 1,
            'isVITA': lambda: 0,
            'isEnableCrossSave': lambda: 0,
            'cfIsMulti': lambda: 0,
            'cfIsMultiStart': lambda: 0,
            'cfIsMultiError': lambda: 0,
            # the stage
            'cfSetEnableHitArea': self._enable_hit_area,
            'cfSetEnableBorderline': self._enable_fence,
            'cfSetEnableEmGen': self._enable_spawner,
            'cfReviveEmGen': lambda n: self._enable_spawner(n, 1),
            'cfAddEmGenWait': lambda n, d: self.note(
                'spawner', '%s delayed by %s frames' % (n, to_string(d))),
            'cfStartPieceLock': self._start_lock,
            'cfEndPieceLock': self._end_lock,
            'cfSetEnemyMax': self._enemy_max,
            # The four questions a quest script asks about what is alive.
            # Without a spawner they are what they were: zero.
            'cfGetCntKillGenPieceLockOnly': lambda: self._ask('kills', 0),
            'getLatestKilled': lambda: self._ask('latest_killed', 0),
            'getNumOfEnemy': lambda *a: self._ask('num_enemy', 0),
            'getNumOfBoss': lambda *a: self._ask('num_boss', 0),
            'cfGetPosInHta': self._hta_axis,
            'getHTAPos': self._hta_pos,
            'cfMapJump': self._map_jump,
            'cfMapJumpForce': self._map_jump,
            'changeEnemySet': self._change_enemy_set,
            'callQuestScriptPC': self.run_source,
            'delayScriptCall': lambda d, s: self.run_source(s),
            # characters
            'getCharacter': self._get_character,
            'chrSetPos': self._chr_set_pos,
            'chrSetRot': self._chr_set_rot,
            'chrGetRot': lambda c: getattr(c, 'rot', 0),
            'chrSetFromHta': self._chr_from_hta,
            'chrSetMotion': self._chr_motion,
            'chrSetMotionNPC': lambda c, m, con=0, f=0: self._chr_motion(c, m),
            'chrVisible': self._chr_visible,
            # the cutscene layer
            'getDemoFrame': lambda: Array([self.demo.get('frame', 0),
                                           self.demo.get('end', 0)]),
            'setDemoID': self._set_demo_id,
            'setDemoEnd': self._set_demo_end,
            'isDemoMode': lambda: 1 if self.demo.get('on') else 0,
            'setDemoMode': lambda v: self.demo.__setitem__('on', bool(v)),
            'setDemoPause': lambda v: self.demo.__setitem__('pause', bool(v)),
            # numbers the scripts branch on
            'cfGetRandI': lambda n: self.rng.randrange(max(1, int(n))),
            'cfGetRandF': lambda n: self.rng.random() * n,
            'getRand': lambda: self.rng.randrange(10001),
            # camera and sound, which are recorded with their argument
            'cfSetCameraType': self._camera_type,
            'cfSetCmrFov': lambda d: self.camera.__setitem__('fov', d),
            'cfSndPlayBGM': lambda slot, cue, fade=0: self._bgm(cue, slot),
            'cfSndPlayStgBGMOW': lambda slot, cue, fade=0: self._bgm(cue,
                                                                     slot),
            'cfSndStopBGM': self._bgm_stop,
            # the blocking calls whose value the host owes the script
            'setWaitCount': self._set_wait,
            # effects
            'effStart': self._eff_start,
            'effSetPos': self._eff_set,
            'effSetRot': self._eff_set,
            # talk: the message and the speaker are both table rows
            'talk_begin': lambda: self.note('talk', 'a conversation opens'),
            'cfTalk': self._talk,
            'cfTalkOpen': self._talk,
            'cfTalkClose': lambda: None,
            'cfTalk_end': lambda: self.note('talk', 'the conversation ends'),
            'cfChoice': self._choice,
            'cfChoiceFreedom': self._choice,
            # the singleton the three test calls address
            'SoundManager_getInstance': self._sound_manager,
        }
        self.implemented = set(real)
        for name, fn in real.items():
            self.vm.register(name, self._counted(name, fn, True))
        for name in NATIVES:
            if name not in self.vm.root.slots:
                self.vm.register(name, self._counted(name, None, False))
        # `callQuestScript` is the trigger's own entry point and is not in the
        # 285 - the triggers call it, the scripts do not.
        self.vm.register('callQuestScript',
                         self._counted('callQuestScript', self.run_source,
                                       True))

    def _counted(self, name, fn, real):
        """One binding, wrapped so it counts and so its arity is Squirrel's.

        Squirrel calls a native with whatever the source wrote and the engine
        reads what it wants; Python raises. `q01106`'s stage script calls
        `cfSetEnableBorderline()` with no arguments at all, which is a
        one-line slip in a hand-written script that the real game shrugs off,
        and a run of 430 quests should not end on it. Missing arguments are
        filled with 0 and extra ones dropped, and every adaptation is
        recorded in `arity` so the report can say it happened.
        """
        table = self.real_calls if real else self.stub_calls
        lo, hi = _arity(fn)

        def call(*args):
            table[name] = table.get(name, 0) + 1
            if fn is None:
                return 0
            if not lo <= len(args) <= hi:
                self.arity[name] = self.arity.get(name, 0) + 1
                args = (tuple(args) + (0,) * lo)[:max(lo, min(len(args), hi))]
            return fn(*args)
        return call

    # -- the implementations ----------------------------------------------

    def _set_counter(self, n):
        self.main_counter = int(n)
        self.note('story', 'the main counter is now %d' % self.main_counter)

    def _enable_hit_area(self, name, on):
        self.hit_areas[name] = bool(on)
        self.note('stage', 'hit area %s %s' % (name,
                                               'on' if on else 'off'))

    def _enable_fence(self, name, on):
        self.fences[name] = bool(on)
        self.note('stage', 'fence %s %s' % (name, 'on' if on else 'off'))

    def _enable_spawner(self, name, on):
        self.spawners[str(name)] = bool(on)
        self.note('stage', 'spawner %s %s' % (name, 'on' if on else 'off'))
        if self.spawner is not None:
            self.spawner.enable(str(name), bool(on))

    def _enemy_max(self, n):
        self.note('stage', 'at most %s alive at once' % to_string(n))
        if self.spawner is not None:
            self.spawner.at_once = int(n)

    def _ask(self, what, default=0):
        """A number only the quest layer knows. `format_api.md` says what
        each of them means; `mission.py` is what has one."""
        if self.spawner is None:
            return default
        return getattr(self.spawner, what)

    def _start_lock(self, name):
        self.piece_lock = str(name)
        self.note('stage', 'piece lock %s closes' % name)
        if self.spawner is not None:
            self.spawner.start_lock(str(name))

    def _end_lock(self):
        self.note('stage', 'piece lock %s opens' % (self.piece_lock or '?'))
        if self.spawner is not None:
            self.spawner.end_lock()
        self.piece_lock = None

    def _hta_axis(self, name, axis):
        m = self._marker(name)
        return float(m.position[int(axis)]) if m else 0.0

    def _hta_pos(self, name):
        m = self._marker(name)
        return Array(list(m.position) if m else [0.0, 0.0, 0.0])

    def _marker(self, name):
        if self.world is None:
            return None
        return self.world.stage.atih.by_name().get(name) if \
            self.world.stage.atih else None

    def _map_jump(self, stage, marker='appear01'):
        self.pending_jump = (str(stage), str(marker))
        self.note('jump', 'to %s at %s' % (stage, marker))

    def _change_enemy_set(self, table, script):
        self.note('stage', 'enemy set %s, then %s' % (table, script))
        return self.run_source(script)

    def _get_character(self, name):
        if name in self.characters:
            return self.characters[name]
        m = self._marker(CHR_PREFIX + str(name))
        c = Character(str(name), m)
        if m is None:
            self.note('cast', '%s stands on no marker' % name)
        self.characters[name] = c
        return c

    def _chr_set_pos(self, c, x, y, z):
        if isinstance(c, Character):
            c.x, c.y, c.z = float(x), float(y), float(z)

    def _chr_set_rot(self, c, a):
        if isinstance(c, Character):
            c.rot = (float(a) % 65536) * 360.0 / 65536.0

    def _chr_from_hta(self, c, name):
        m = self._marker(str(name))
        if isinstance(c, Character) and m:
            c.x, c.y, c.z = m.position
            c.rot = m.rotation[1]

    def _chr_motion(self, c, motion, force=0):
        if isinstance(c, Character):
            c.motion = None if int(motion) == 201 else int(motion)

    def _chr_visible(self, c, on):
        if isinstance(c, Character):
            c.visible = bool(on)

    def _set_demo_id(self, demo_id, kind=0):
        self.demo['id'] = int(demo_id)
        self.note('demo', 'cutscene %d' % int(demo_id))

    def _set_demo_end(self):
        self.demo['ended'] = True
        self.note('demo', 'the cutscene ends')

    def _camera_type(self, kind, a=0, b=0):
        self.camera['type'] = kind
        self.note('camera', 'type %s' % to_string(kind))

    def _bgm(self, cue, slot=0):
        self.bgm = cue
        self.note('sound', 'BGM cue %s on slot %s' % (to_string(cue),
                                                      to_string(slot)))

    def _bgm_stop(self, slot=0, fade=0):
        self.note('sound', 'BGM stops over %s frames' % to_string(fade))
        self.bgm = None

    def _set_wait(self, n):
        self.wait_count = int(n)

    def _eff_start(self, category, slot):
        h = Table({'category': category, 'slot': slot})
        self.effects.append(h)
        self.note('effect', 'category %s slot %s' % (to_string(category),
                                                     to_string(slot)))
        return h

    def _eff_set(self, handle, a, b, c):
        return None

    def _table_text(self, rel, cache={}):
        if rel not in cache:
            p = self.tree / rel
            cache[rel] = Rmsg(p.read_bytes(), rel).texts if p.is_file() else []
        return cache[rel]

    def _talk(self, who, msg):
        names = self._table_text(TALK_WHO)
        lines = self._table_text(TALK_MSG)
        who, msg = int(who), int(msg)
        name = names[who] if 0 <= who < len(names) else '#%d' % who
        text = lines[msg] if 0 <= msg < len(lines) else '#%d' % msg
        self.note('talk', '%s: %s' % (name, text.replace(chr(10), ' / ')))

    def _choice(self, sel):
        self.note('talk', 'a choice, list %s - the host takes the first'
                  % to_string(sel))

    def _sound_manager(self):
        t = Table()
        t.slots['setVolumeCategory'] = Native(
            'setVolumeCategory', lambda *a: None)
        t.slots['Print'] = Native('Print', lambda *a: None)
        return t

    # -- loading -----------------------------------------------------------

    def load_script(self, rel):
        p = self.tree / rel
        if not p.is_file():
            return False
        q = Psq(p.read_bytes(), rel)
        self.wanted |= globals_called(q.root)
        self.vm.load(q.root, rel)
        self.loaded.append(rel)
        return True

    def load_common(self):
        for name in LIBRARY:
            self.load_script('misc.cpk/psq_common.pac/' + name)

    def enter_stage(self, name, marker='appear01'):
        """Load a stage's world and its scripts, and call `sfStageInit`."""
        d = self.tree / 'stage.cpk' / name / 'param.pac'
        if not d.is_dir():
            raise SystemExit('no stage %s under %s' % (name, self.tree))
        self.world = World(d)
        self.stage_name = name
        self.characters.clear()
        self.hit_areas = {m.name: True for m in self.world.stage.markers}
        if self.spawner is not None:
            self.spawner.enter(name, self.world)
        self.note('stage', 'entered %s at %s (%d markers, %d triggers)'
                  % (name, marker, len(self.world.stage.markers),
                     len(self.world.stage.triggers)))
        # A stage's own `param.pac` may ship more than one script - the
        # town ships its NPC layer beside its stage layer - and both are
        # resident. Its *conversations* are not: the 460 scripts under
        # `140_02_01` collide on 147 names, seventeen of them defining
        # `talkNornThanks`, so the host loads one when a conversation starts.
        for q in sorted((d).glob('*.psq')):
            self.load_script('stage.cpk/%s/param.pac/%s' % (name, q.name))
        if self.quest:
            self.load_script('quest.cpk/%s.pac/%s.psq' % (self.quest, name))
        for fn in ('sfStageInit', 'sfQuestInit'):
            self.call(fn, why=fn)
        return self.world

    # -- running scripts ---------------------------------------------------

    def call(self, name, args=(), why=''):
        """Call a script function, and keep the thread if it suspends."""
        fn = self.vm.find(name)
        if not isinstance(fn, Closure):
            return None
        th = Thread(self.vm, name)
        try:
            th.start(fn, list(args))
        except SquirrelError as e:
            self.note('error', '%s: %s' % (name, e))
            return th
        self.steps += th.steps
        if th.state == 'suspended':
            self._park(th, why or name)
        return th

    def run_source(self, text):
        """Run a line of trigger source: a sequence of calls."""
        calls = call_line(to_string(text))
        if calls is None:
            self.note('error', 'cannot read trigger source %r' % text)
            return 0
        for name, args in calls:
            fn = self.vm.find(name)
            if fn is None:
                self.note('error', 'the trigger calls %s, which nothing '
                                   'defines' % name)
                continue
            if isinstance(fn, Native):
                fn.fn(*args)
                continue
            self.call(name, args, why='trigger %s' % name)
        return 0

    def _park(self, th, why):
        n = self.value_of_suspend(th.value)
        delay, value, what = n
        wake = self.frame + (self.wait_count if delay == 'wait' else delay)
        self.threads.append([th, wake, value, what, why])
        self.note('suspend', '%s waits on %s (%s), %d frames'
                  % (why, to_string(th.value), what,
                     max(0, wake - self.frame)))

    def value_of_suspend(self, n):
        if isinstance(n, int) and n in RESUME:
            return RESUME[n]
        return (0, None, 'unknown suspend %s' % to_string(n))

    def tick_threads(self):
        for row in list(self.threads):
            th, wake, value, what, why = row
            if self.frame < wake:
                continue
            self.threads.remove(row)
            before = th.steps
            try:
                th.resume(value)
                self.steps += th.steps - before
            except SquirrelError as e:
                self.note('error', '%s: %s' % (why, e))
                continue
            if th.state == 'suspended':
                self._park(th, why)

    # -- the frame ---------------------------------------------------------

    def triggers_at(self, x, y, z):
        """Which trigger volumes contain a point, of the ones still on."""
        out = []
        by_name = self.world.stage.atih.by_name()
        for t in self.world.stage.triggers:
            m = by_name.get(t.name)
            if m is None or not m.volume:
                continue
            if not self.hit_areas.get(t.name, True):
                continue
            if inside(m, x, y, z):
                out.append(t)
        return out


# -- the milestone ---------------------------------------------------------


def cmd_stage(tree, stage='010_01_01', quest='q00101',
              json_path='job.cpk/sw/sw.json', gait='run', limit=3000) -> int:
    """Milestone 2: a stage runs.

    The stage's script initialises it, a body with the game's own parameters
    walks it, the trigger volumes fire the functions their own `trigger.trg`
    names, and a `cfMapJump` loads the next stage and starts it too."""
    host = Host(tree, quest=quest)
    host.load_common()
    host.enter_stage(stage)
    params = load_params(host.tree / json_path)

    m = host.world.marker('appear01')
    act = Actor(params, m.position[0], m.position[1], m.position[2],
                m.rotation[1])
    goal = _exit_of(host.world)
    host.note('walk', 'from appear01 towards %s, %.1f m away'
              % (goal.name, math.hypot(m.position[0] - goal.position[0],
                                       m.position[2] - goal.position[2])))
    inside_now = set()
    stages = [stage]
    off_mesh = 0
    for _ in range(limit):
        host.frame += 1
        host.tick_threads()
        head = bearing(act.x, act.z, goal.position[0], goal.position[2])
        r = act.step(host.world, gait=gait, facing=head)
        if r['event'].startswith('off'):
            off_mesh += 1
        now = {t.name: t for t in host.triggers_at(act.x, act.y, act.z)}
        for name, t in now.items():
            if name in inside_now:
                continue
            if t.kind in (0, 1):
                host.note('trigger', 'entered %s: %s' % (name, t.script))
                host.run_source(t.script)
        for name in list(inside_now):
            if name not in now:
                t = next((x for x in host.world.stage.triggers
                          if x.name == name), None)
                if t is not None and t.kind == 2:
                    host.note('trigger', 'left %s: %s' % (name, t.script))
                    host.run_source(t.script)
        inside_now = set(now)
        if host.pending_jump:
            nxt, arrive = host.pending_jump
            host.pending_jump = None
            if not (host.tree / 'stage.cpk' / nxt / 'param.pac').is_dir():
                host.note('jump', '%s is not on the disc - stopping' % nxt)
                break
            host.enter_stage(nxt, arrive)
            stages.append(nxt)
            m = host.world.marker(arrive)
            act = Actor(params, m.position[0], m.position[1], m.position[2],
                        m.rotation[1])
            goal = _exit_of(host.world)
            inside_now = set()
            host.note('walk', 'from %s towards %s' % (arrive, goal.name))
            if len(stages) >= 2:
                break                           # one jump is the milestone
    fired = sum(1 for f, k, t in host.events if k == 'trigger')
    volumes = sum(1 for t in host.world.stage.triggers)
    print()
    print('  %d frames = %.2f s, %d stages: %s'
          % (host.frame, host.frame / FPS, len(stages), ' -> '.join(stages)))
    print('  %d scripts loaded: %s'
          % (len(host.loaded),
             ', '.join(p.rsplit('/', 1)[-1] for p in host.loaded)))
    print('  %d instructions retired, %d host calls, %d trigger volumes on '
          'the last stage and %d fired'
          % (host.steps,
             sum(host.real_calls.values()) + sum(host.stub_calls.values()),
             volumes, fired))
    reached = set(host.real_calls) | set(host.stub_calls)
    print('  %d of the 285 reached: %d that do something, %d recorded as '
          'stubs' % (len(reached & set(NATIVES)),
                     len(set(host.real_calls) & set(NATIVES)),
                     len(set(host.stub_calls) & set(NATIVES))))
    print('  %d frames with no ground underneath' % off_mesh)
    if host.missing:
        print('  %d names called that nothing loaded defines: %s'
              % (len(host.missing), ', '.join(sorted(host.missing))))
    if host.threads:
        print('  %d threads still inside a suspend: %s'
              % (len(host.threads), ', '.join(t[4] for t in host.threads)))
    return 0


def _exit_of(world):
    for m in world.stage.markers:
        if m.kind.startswith('jump_'):
            return m
    return world.stage.markers[0]


def demo_length(pac):
    """A cutscene's length in frames, off its own camera track."""
    for c in sorted(pathlib.Path(pac).glob('*.CSCM')):
        b = c.read_bytes()
        if b[:4] == b'CSCM' and len(b) > CSCM_FRAMES + 2:
            return int.from_bytes(b[CSCM_FRAMES:CSCM_FRAMES + 2], 'big')
    return None


def run_demo(host, rel, frames, over=120):
    """The cutscene protocol: `demoInitBGM`, `demoInit`, then `demoUpdate`
    once a frame until the script says `setDemoEnd`, then `demoEnd`."""
    host.demo = {'on': True, 'frame': 0, 'end': frames}
    host.load_script(rel)
    for fn in ('demoInitBGM', 'demoInit'):
        host.call(fn, why=fn)
    ended = None
    for f in range(frames + over):
        host.frame = f
        host.demo['frame'] = f
        host.tick_threads()
        host.call('demoUpdate', why='demoUpdate')
        if host.demo.get('ended'):
            ended = f
            break
    host.call('demoEnd', why='demoEnd')
    return ended


def cmd_demo(tree, want='*', verbose='1') -> int:
    """Run a cutscene script against its own camera track.

    The check is behavioural and it is the sharpest one here: a cutscene
    script is a phase machine that counts frames, and driving it with the
    length its own `.CSCM` declares either brings it to `setDemoEnd` or does
    not. Nothing about that is arranged - the script's thresholds are the
    author's and the length is the camera track's."""
    root = pathlib.Path(tree) / 'demo.cpk'
    pacs = sorted(p for p in root.iterdir() if p.is_dir())
    ran = ended = nolength = 0
    late = []
    one = not fnmatch_all(want)
    for pac in pacs:
        if not fnmatch.fnmatch(pac.name, want if want.endswith('.pac')
                               else want + '.pac'):
            continue
        psq = [q for q in pac.glob('*.psq')]
        if not psq:
            continue
        frames = demo_length(pac)
        if frames is None:
            nolength += 1
            continue
        host = Host(tree, verbose=(one and verbose != '0'))
        host.load_common()
        rel = psq[0].relative_to(pathlib.Path(tree)).as_posix()
        try:
            at = run_demo(host, rel, frames)
        except (SquirrelError, VMError) as e:
            print('  %-28s %s' % (pac.name, e))
            continue
        ran += 1
        if at is not None:
            ended += 1
            late.append((at - frames, pac.name, at, frames))
        if one:
            print()
            print('  %s: %d frames of camera track, the script ended at %s'
                  % (pac.name, frames, at if at is not None else 'no end'))
            print('  %d instructions retired, %d host calls'
                  % (host.steps, sum(host.real_calls.values())
                     + sum(host.stub_calls.values())))
            reached = (set(host.real_calls) | set(host.stub_calls))                 & set(NATIVES)
            print('  %d of the 285 reached: %s'
                  % (len(reached), ', '.join(sorted(reached))))
    if not one:
        print('%d cutscenes driven by their own camera track, %d reached '
              'setDemoEnd, %d have no track' % (ran, ended, nolength))
        late.sort()
        for d, name, at, frames in late[:3] + late[-3:]:
            print('  %-28s ended at %4d of %4d' % (name, at, frames))
    return 0


def fnmatch_all(want):
    return want in ('*', '')


def cmd_talk(tree, script, func='', stage='140_02_01') -> int:
    """Run one conversation, and print it.

    This is the `suspend` protocol end to end: `talk(speaker, message)` is
    `cfTalk(...); suspend(101)`, so the script stops on every line and the
    host resumes it a frame later. The text comes from the two tables
    [`format_api.md`](../docs/format_api.md) joins the arguments to."""
    host = Host(tree, quest='')
    host.load_common()
    host.enter_stage(stage)
    rel = script if '/' in script else None
    if rel is None:
        found = list((pathlib.Path(tree)).rglob(script))
        if not found:
            raise SystemExit('no script named ' + script)
        rel = found[0].relative_to(pathlib.Path(tree)).as_posix()
    host.load_script(rel)
    name = func or rel.rsplit('/', 1)[-1].rsplit('.', 1)[0]
    host.note('talk', 'calling %s()' % name)
    host.call(name, why=name)
    while host.threads and host.frame < 20000:
        host.frame += 1
        host.tick_threads()
    lines = sum(1 for f, k, t in host.events if k == 'talk')
    print()
    print('  %d frames, %d instructions retired, %d host calls'
          % (host.frame, host.steps,
             sum(host.real_calls.values()) + sum(host.stub_calls.values())))
    print('  %d lines of conversation, %d threads still waiting'
          % (lines, len(host.threads)))
    reached = (set(host.real_calls) | set(host.stub_calls)) & set(NATIVES)
    print('  %d of the 285 reached: %s'
          % (len(reached), ', '.join(sorted(reached))))
    return 0


def cmd_stages(tree, want='*') -> int:
    """Load every stage's world and script and call `sfStageInit`."""
    root = pathlib.Path(tree) / 'stage.cpk'
    names = sorted(p.name for p in root.iterdir()
                   if (p / 'param.pac').is_dir())
    ok = withscript = failed = clash = 0
    trig = readable = 0
    unbound = {}
    for name in names:
        if not pathlib.Path(tree).joinpath(
                'stage.cpk', name, 'param.pac', 'hta.bin').is_file():
            continue
        host = Host(tree, verbose=False)
        try:
            host.load_common()
            host.enter_stage(name)
        except (SquirrelError, VMError, SystemExit, ValueError) as e:
            failed += 1
            print('  %-12s %s' % (name, e))
            continue
        ok += 1
        withscript += any('/%s.psq' % name in p for p in host.loaded)
        for t in host.world.stage.triggers:
            trig += 1
            readable += call_line(t.script) is not None
        for n in host.missing:
            unbound[n] = unbound.get(n, 0) + 1
        clash += len(host.vm.collisions)
    print('%d stages: %d loaded and initialised, %d with a script of their '
          'own, %d failed' % (len(names), ok, withscript, failed))
    print('%d trigger lines, %d of them read as calls with constant '
          'arguments' % (trig, readable))
    print('%d names defined twice over a stage and the resident library'
          % clash)
    print('%d names called that nothing binds%s'
          % (len(unbound), ': ' + ', '.join(sorted(unbound)) if unbound
             else ''))
    return 1 if failed else 0


def cmd_api(tree) -> int:
    """The interface, and how much of it this file answers."""
    host = Host(tree, verbose=False)
    bound = [n for n in NATIVES if n in host.vm.root.slots]
    real = sorted(set(host.implemented) & set(NATIVES))
    print('%d functions in the interface, %d bound, %d of them doing '
          'something' % (len(NATIVES), len(bound), len(real)))
    print('%d calls a run of the whole disc would make through the %d that '
          'do something, of %d in total'
          % (sum(NATIVES[n] for n in real), len(real),
             sum(NATIVES.values())))
    for n in real:
        print('  %6d  %s' % (NATIVES[n], n))
    missing = sorted(set(NATIVES) - set(bound))
    if missing:
        print('not bound: %s' % ', '.join(missing))
    return 0


def main() -> int:
    a = sys.argv[1:]
    if not a:
        print(__doc__)
        return 2
    cmd, rest = a[0], a[1:]
    if cmd == 'stage' and rest:
        return cmd_stage(*rest)
    if cmd == 'demo' and rest:
        return cmd_demo(*rest)
    if cmd == 'talk' and len(rest) >= 2:
        return cmd_talk(*rest)
    if cmd == 'stages' and rest:
        return cmd_stages(*rest)
    if cmd == 'api' and rest:
        return cmd_api(*rest)
    print(__doc__)
    return 2


if __name__ == '__main__':
    raise SystemExit(main())
